<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="New Collection Copy" tests="1" time="0.000">
  <testsuite name="New Request" id="912fc033-acd8-4139-848b-900b26e8d907" timestamp="2022-03-02T04:12:41.746Z" tests="1" failures="1" errors="1" time="0.000">
    <system-err><![CDATA[Iteration: 0
RequestError: Error: getaddrinfo EAI_AGAIN apitestingproject
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

---
]]></system-err>
    <testcase name="Status code is 200" time="0.000" classname="NewCollectionCopy">
      <failure type="AssertionFailure" message="expected { Object (id, _details, ...) } to have property 'code'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 8c9f56ee-91b6-497e-a362-70d7b39d28e9.]]>
        <![CDATA[Collection name: New Collection Copy.]]>
        <![CDATA[Request name: New Request.]]>
        <![CDATA[Test description: Status code is 200.]]>
        <![CDATA[Error message: expected { Object (id, _details, ...) } to have property 'code'.]]>
        <![CDATA[Stacktrace: AssertionError: expected { Object (id, _details, ...) } to have property 'code'
   at Object.eval sandbox-script.js:1:1).]]>
      </failure>
    </testcase>
  </testsuite>
</testsuites>